# -*- coding: utf-8 -*-
"""face detection

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DEgvyJVzTtxggaAWgrU8jAbLTdpBKbJ
"""

import numpy as np



import matplotlib.pyplot as plt

img=plt.imread("/content/youngerteens-400x232.jpg")#add image url here

plt.imshow(img)

img.shape

import cv2

model=cv2.CascadeClassifier("/content/haarcascade_frontalface_default.xml")

faces=model.detectMultiScale(img)

faces

faces.shape

for face in faces:
  x,y,w,h = face

  img=cv2.rectangle(img,(x,y),(x+w,y+h),(0,0,0),2)

plt.imshow(img)

