/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:lista:990771:
  println("dropList1 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:lista:990771:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:496080:
  int index = lista.getSelectedIndex();
  switch(index){
  case 0:
    li = 8;
    ls = 8;
    board = new Tile[8][8];
    nbomb = 10;
  break;
  case 1:
    li = 16;
    ls = 16;
    nbomb = 40;
    board = new Tile[16][16];
  break;
  case 2:
    li = 16;
    ls = 30;
    board = new Tile[16][30];
    nbomb = 99;
  break;
  }
  setgame();
} //_CODE_:button1:496080:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("minesweeper");
  label1 = new GLabel(this, -2, 0, 341, 33);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Minesweeper");
  label1.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  label1.setOpaque(true);
  lista = new GDropList(this, 6, 4, 90, 80, 3, 10);
  lista.setItems(loadStrings("list_990771"), 0);
  lista.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  lista.addEventHandler(this, "dropList1_click1");
  button1 = new GButton(this, 281, 5, 47, 18);
  button1.setText("play");
  button1.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  button1.addEventHandler(this, "button1_click1");
}

// Variable declarations 
// autogenerated do not edit
GLabel label1; 
GDropList lista; 
GButton button1; 
